@@ -0,0 +1,23 @@
# fly.toml app configuration file generated for conta-service on 2025-03-30T01:59:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'conta-service'
primary_region = 'gig'

[build]

[http_service]
  internal_port = 9000
  force_https = false
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024